version: "3.8"

services:
  api:
    build: ../
    container_name: docker-learning-server
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
      - /app/node_modules
  client:
    build: ../client
    container_name: docker-learning-client
    ports:
      - "3000:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
